/* =========================================================
   TableScript
   작성자: 송경민

   목차
   1. DROP
   2. 기준 / 공통
      - 사용자
      - 점포
      - 파일
      - 자재
      - 점포 재고
   3. 발주
      - 발주
      - 발주 상세
      - 발주 상태 이력
   4. 입고
      - 입고
      - 입고 상세
   5. 점포 마감
      - 점포 마감
      - 점포 마감 상세
   6. 재고 변동 이력
      - 재고 변동 이력
      - 재고 변동 이력 상세
   7. 공지사항
      - 공지사항
      - 공지사항 파일
   8. 문의사항
      - 문의사항
      - 문의사항 파일
   9. 데이터 시딩
      - 관리자 계정
      - 점주 1 계정
   ========================================================= */


-- =========================================================
-- 1. DROP
-- =========================================================

-- 문의사항
DROP TABLE INQUIRY_FILES CASCADE CONSTRAINTS;
DROP TABLE INQUIRIES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INQ_FILE;
DROP SEQUENCE SEQ_INQ;

-- 공지사항
DROP TABLE NOTICE_FILES CASCADE CONSTRAINTS;
DROP TABLE NOTICES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_NOTICE_FILE;
DROP SEQUENCE SEQ_NOTICE;

-- 재고 변동 이력
DROP TABLE INVENTORY_TRANSACTION_ITEMS CASCADE CONSTRAINTS;
DROP TABLE INVENTORY_TRANSACTIONS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INV_TX_ITEM;
DROP SEQUENCE SEQ_INV_TX;

-- 점포 마감
DROP TABLE STORE_CLOSING_ITEMS CASCADE CONSTRAINTS;
DROP TABLE STORE_CLOSINGS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STORE_CLS_ITEM;
DROP SEQUENCE SEQ_STORE_CLS;

-- 입고
DROP TABLE RECEIPT_ITEMS CASCADE CONSTRAINTS;
DROP TABLE RECEIPTS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_RECEIPT_ITEM;
DROP SEQUENCE SEQ_RECEIPT;

-- 발주
DROP TABLE PURCHASE_REQUEST_HISTORIES CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_REQUEST_ITEMS CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_REQUESTS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PUR_REQ_HIST;
DROP SEQUENCE SEQ_PUR_REQ_ITEM;
DROP SEQUENCE SEQ_PUR_REQ;

-- 점포 재고
DROP TABLE STORE_INVENTORIES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STORE_INV;

-- 자재
DROP TABLE MATERIALS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MATERIAL;

-- 파일
DROP TABLE FILES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_FILE;

-- 점포
DROP TABLE STORES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STORE;

-- 사용자
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_USER;


-- =========================================================
-- 2. 기준 / 공통
-- =========================================================

-- 사용자
CREATE TABLE USERS (
    USER_ID    NUMBER NOT NULL
    , LOGIN_ID   VARCHAR2(50) NOT NULL
    , PASSWORD   VARCHAR2(255) NOT NULL
    , USER_NAME  VARCHAR2(50) NOT NULL
    , PHONE      VARCHAR2(30)
    , EMAIL      VARCHAR2(100)
    , ROLE       VARCHAR2(20) DEFAULT 'OWNER' NOT NULL
    , STATUS     VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
    , CREATED_BY NUMBER
    , CREATED_AT DATE DEFAULT SYSDATE NOT NULL
    , UPDATED_BY NUMBER
    , UPDATED_AT DATE
    , CONSTRAINT PK_USERS PRIMARY KEY ( USER_ID )
    , CONSTRAINT UK_USERS_LOGIN_ID UNIQUE ( LOGIN_ID )
    , CONSTRAINT CK_USERS_ROLE CHECK ( ROLE IN ( 'OWNER', 'ADMIN' ) )
    , CONSTRAINT CK_USERS_STATUS CHECK ( STATUS IN ( 'ACTIVE', 'INACTIVE' ) )
);

CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE USERS IS
    '사용자';
COMMENT ON COLUMN USERS.USER_ID IS
    '사용자 ID';
COMMENT ON COLUMN USERS.LOGIN_ID IS
    '로그인 ID';
COMMENT ON COLUMN USERS.PASSWORD IS
    '비밀번호';
COMMENT ON COLUMN USERS.USER_NAME IS
    '사용자명';
COMMENT ON COLUMN USERS.PHONE IS
    '전화번호';
COMMENT ON COLUMN USERS.EMAIL IS
    '이메일';
COMMENT ON COLUMN USERS.ROLE IS
    '역할';
COMMENT ON COLUMN USERS.STATUS IS
    '사용자 상태';
COMMENT ON COLUMN USERS.CREATED_BY IS
    '등록자 ID';
COMMENT ON COLUMN USERS.CREATED_AT IS
    '등록일시';
COMMENT ON COLUMN USERS.UPDATED_BY IS
    '수정자 ID';
COMMENT ON COLUMN USERS.UPDATED_AT IS
    '수정일시';

-- 점포
CREATE TABLE STORES (
    STORE_ID      NUMBER NOT NULL
    , STORE_CODE    VARCHAR2(30) NOT NULL
    , STORE_NAME    VARCHAR2(100) NOT NULL
    , PHONE         VARCHAR2(30)
    , ADDRESS       VARCHAR2(255) NOT NULL
    , OWNER_USER_ID NUMBER NOT NULL
    , STATUS        VARCHAR2(20) DEFAULT 'OPEN' NOT NULL
    , CREATED_BY    NUMBER
    , CREATED_AT    DATE DEFAULT SYSDATE NOT NULL
    , UPDATED_BY    NUMBER
    , UPDATED_AT    DATE
    , CONSTRAINT PK_STORES PRIMARY KEY ( STORE_ID )
    , CONSTRAINT UK_STORES_CODE UNIQUE ( STORE_CODE )
    , CONSTRAINT UK_STORES_OWNER UNIQUE ( OWNER_USER_ID )
    , CONSTRAINT CK_STORES_STATUS CHECK ( STATUS IN ( 'OPEN', 'CLOSED' ) )
    , CONSTRAINT FK_STORES_OWNER FOREIGN KEY ( OWNER_USER_ID )
        REFERENCES USERS ( USER_ID )
);

CREATE SEQUENCE SEQ_STORE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORES IS
    '점포';
COMMENT ON COLUMN STORES.STORE_ID IS
    '점포 ID';
COMMENT ON COLUMN STORES.STORE_CODE IS
    '점포 코드';
COMMENT ON COLUMN STORES.STORE_NAME IS
    '점포명';
COMMENT ON COLUMN STORES.PHONE IS
    '점포 전화번호';
COMMENT ON COLUMN STORES.ADDRESS IS
    '점포 주소';
COMMENT ON COLUMN STORES.OWNER_USER_ID IS
    '점주 사용자 ID';
COMMENT ON COLUMN STORES.STATUS IS
    '점포 상태';
COMMENT ON COLUMN STORES.CREATED_BY IS
    '등록자 ID';
COMMENT ON COLUMN STORES.CREATED_AT IS
    '등록일시';
COMMENT ON COLUMN STORES.UPDATED_BY IS
    '수정자 ID';
COMMENT ON COLUMN STORES.UPDATED_AT IS
    '수정일시';


-- 파일
CREATE TABLE FILES (
    FILE_ID       NUMBER NOT NULL
    , ORIGINAL_NAME VARCHAR2(255) NOT NULL
    , STORED_NAME   VARCHAR2(255) NOT NULL
    , STORAGE_PATH  VARCHAR2(500) NOT NULL
    , MIME_TYPE     VARCHAR2(100)
    , FILE_SIZE     NUMBER
    , DELETED_AT    DATE
    , CREATED_BY    NUMBER NOT NULL
    , CREATED_AT    DATE DEFAULT SYSDATE NOT NULL
    , CONSTRAINT PK_FILES PRIMARY KEY ( FILE_ID )
);

CREATE SEQUENCE SEQ_FILE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE FILES IS
    '파일';
COMMENT ON COLUMN FILES.FILE_ID IS
    '파일 ID';
COMMENT ON COLUMN FILES.ORIGINAL_NAME IS
    '원본 파일명';
COMMENT ON COLUMN FILES.STORED_NAME IS
    '저장 파일명';
COMMENT ON COLUMN FILES.STORAGE_PATH IS
    '저장 경로';
COMMENT ON COLUMN FILES.MIME_TYPE IS
    'MIME 타입';
COMMENT ON COLUMN FILES.FILE_SIZE IS
    '파일 크기';
COMMENT ON COLUMN FILES.DELETED_AT IS
    '삭제일시';
COMMENT ON COLUMN FILES.CREATED_BY IS
    '등록자 ID';
COMMENT ON COLUMN FILES.CREATED_AT IS
    '등록일시';


-- 자재
CREATE TABLE MATERIALS (
    MATERIAL_ID   NUMBER NOT NULL
    , MATERIAL_CODE VARCHAR2(30) NOT NULL
    , MATERIAL_NAME VARCHAR2(100) NOT NULL
    , MATERIAL_TYPE VARCHAR2(50)
    , UNIT_PRICE    NUMBER(12) DEFAULT 0 NOT NULL
    , IMAGE_FILE_ID NUMBER
    , STATUS        VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
    , CREATED_BY    NUMBER
    , CREATED_AT    DATE DEFAULT SYSDATE NOT NULL
    , UPDATED_BY    NUMBER
    , UPDATED_AT    DATE
    , CONSTRAINT PK_MATERIALS PRIMARY KEY ( MATERIAL_ID )
    , CONSTRAINT UK_MATERIALS_CODE UNIQUE ( MATERIAL_CODE )
    , CONSTRAINT CK_MATERIALS_STATUS CHECK ( STATUS IN ( 'ACTIVE', 'INACTIVE' ) )
    , CONSTRAINT FK_MATERIALS_FILE FOREIGN KEY ( IMAGE_FILE_ID )
        REFERENCES FILES ( FILE_ID )
);

CREATE SEQUENCE SEQ_MATERIAL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE MATERIALS IS
    '자재';
COMMENT ON COLUMN MATERIALS.MATERIAL_ID IS
    '자재 ID';
COMMENT ON COLUMN MATERIALS.MATERIAL_CODE IS
    '자재 코드';
COMMENT ON COLUMN MATERIALS.MATERIAL_NAME IS
    '자재명';
COMMENT ON COLUMN MATERIALS.MATERIAL_TYPE IS
    '자재 유형';
COMMENT ON COLUMN MATERIALS.UNIT_PRICE IS
    '단가';
COMMENT ON COLUMN MATERIALS.IMAGE_FILE_ID IS
    '이미지 파일 ID';
COMMENT ON COLUMN MATERIALS.STATUS IS
    '자재 상태';
COMMENT ON COLUMN MATERIALS.CREATED_BY IS
    '등록자 ID';
COMMENT ON COLUMN MATERIALS.CREATED_AT IS
    '등록일시';
COMMENT ON COLUMN MATERIALS.UPDATED_BY IS
    '수정자 ID';
COMMENT ON COLUMN MATERIALS.UPDATED_AT IS
    '수정일시';


-- 점포 재고
CREATE TABLE STORE_INVENTORIES (
    STORE_INVENTORY_ID NUMBER NOT NULL
    , STORE_ID           NUMBER NOT NULL
    , MATERIAL_ID        NUMBER NOT NULL
    , CURRENT_QUANTITY   NUMBER(10) DEFAULT 0 NOT NULL
    , SAFETY_QUANTITY    NUMBER(10) DEFAULT 0 NOT NULL
    , CREATED_BY         NUMBER
    , CREATED_AT         DATE DEFAULT SYSDATE NOT NULL
    , UPDATED_BY         NUMBER
    , UPDATED_AT         DATE
    , CONSTRAINT PK_STORE_INV PRIMARY KEY ( STORE_INVENTORY_ID )
    , CONSTRAINT UK_STORE_INV_MAT UNIQUE ( STORE_ID
    , MATERIAL_ID )
    , CONSTRAINT FK_STORE_INV_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
    , CONSTRAINT FK_STORE_INV_MAT FOREIGN KEY ( MATERIAL_ID )
        REFERENCES MATERIALS ( MATERIAL_ID )
);

CREATE SEQUENCE SEQ_STORE_INV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORE_INVENTORIES IS
    '점포 재고';
COMMENT ON COLUMN STORE_INVENTORIES.STORE_INVENTORY_ID IS
    '점포 재고 ID';
COMMENT ON COLUMN STORE_INVENTORIES.STORE_ID IS
    '점포 ID';
COMMENT ON COLUMN STORE_INVENTORIES.MATERIAL_ID IS
    '자재 ID';
COMMENT ON COLUMN STORE_INVENTORIES.CURRENT_QUANTITY IS
    '현재 재고 수량';
COMMENT ON COLUMN STORE_INVENTORIES.SAFETY_QUANTITY IS
    '안전 재고 수량';
COMMENT ON COLUMN STORE_INVENTORIES.CREATED_BY IS
    '등록자 ID';
COMMENT ON COLUMN STORE_INVENTORIES.CREATED_AT IS
    '등록일시';
COMMENT ON COLUMN STORE_INVENTORIES.UPDATED_BY IS
    '수정자 ID';
COMMENT ON COLUMN STORE_INVENTORIES.UPDATED_AT IS
    '수정일시';


-- =========================================================
-- 3. 발주
-- =========================================================

-- 발주
CREATE TABLE PURCHASE_REQUESTS (
    PURCHASE_REQUEST_ID NUMBER NOT NULL
    , STORE_ID            NUMBER NOT NULL
    , STATUS              VARCHAR2(30) DEFAULT 'REQUESTED' NOT NULL
    , TOTAL_AMOUNT        NUMBER(12) DEFAULT 0 NOT NULL
    , REQUEST_MEMO        VARCHAR2(1000)
    , CREATED_BY          NUMBER NOT NULL
    , CREATED_AT          DATE DEFAULT SYSDATE NOT NULL
    , UPDATED_BY          NUMBER
    , UPDATED_AT          DATE
    , CONSTRAINT PK_PUR_REQ PRIMARY KEY ( PURCHASE_REQUEST_ID )
    , CONSTRAINT CK_PUR_REQ_STATUS
        CHECK ( STATUS IN ( 'REQUESTED', 'PARTIALLY_APPROVED', 'APPROVED', 'REJECTED', 'CANCELED', 'RECEIVED' ) )
    , CONSTRAINT FK_PUR_REQ_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
    , CONSTRAINT FK_PUR_REQ_USER FOREIGN KEY ( CREATED_BY )
        REFERENCES USERS ( USER_ID )
);

CREATE SEQUENCE SEQ_PUR_REQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE PURCHASE_REQUESTS IS
    '발주 요청';
COMMENT ON COLUMN PURCHASE_REQUESTS.PURCHASE_REQUEST_ID IS
    '발주 요청 ID';
COMMENT ON COLUMN PURCHASE_REQUESTS.STORE_ID IS
    '점포 ID';
COMMENT ON COLUMN PURCHASE_REQUESTS.STATUS IS
    '발주 상태';
COMMENT ON COLUMN PURCHASE_REQUESTS.TOTAL_AMOUNT IS
    '총 금액';
COMMENT ON COLUMN PURCHASE_REQUESTS.REQUEST_MEMO IS
    '발주 요청 메모';
COMMENT ON COLUMN PURCHASE_REQUESTS.CREATED_BY IS
    '등록자 ID';
COMMENT ON COLUMN PURCHASE_REQUESTS.CREATED_AT IS
    '등록일시';
COMMENT ON COLUMN PURCHASE_REQUESTS.UPDATED_BY IS
    '수정자 ID';
COMMENT ON COLUMN PURCHASE_REQUESTS.UPDATED_AT IS
    '수정일시';


-- 발주 상세
CREATE TABLE PURCHASE_REQUEST_ITEMS (
    PURCHASE_REQUEST_ITEM_ID NUMBER NOT NULL
    , PURCHASE_REQUEST_ID      NUMBER NOT NULL
    , MATERIAL_ID              NUMBER NOT NULL
    , MATERIAL_NAME_SNAPSHOT   VARCHAR2(100) NOT NULL
    , UNIT_PRICE_SNAPSHOT      NUMBER(12) NOT NULL
    , REQUEST_QUANTITY         NUMBER(10) NOT NULL
    , APPROVED_QUANTITY        NUMBER(10) DEFAULT 0 NOT NULL
    , ITEM_STATUS              VARCHAR2(30) DEFAULT 'REQUESTED' NOT NULL
    , REJECT_REASON            VARCHAR2(1000)
    , SUBTOTAL_AMOUNT          NUMBER(12) DEFAULT 0 NOT NULL
    , CONSTRAINT PK_PUR_REQ_ITEM PRIMARY KEY ( PURCHASE_REQUEST_ITEM_ID )
    , CONSTRAINT UK_PUR_REQ_ITEM_MAT UNIQUE ( PURCHASE_REQUEST_ID
    , MATERIAL_ID )
    , CONSTRAINT CK_PUR_REQ_ITEM_STATUS
        CHECK ( ITEM_STATUS IN ( 'REQUESTED', 'APPROVED', 'REJECTED' ) )
    , CONSTRAINT FK_PUR_ITEM_REQ FOREIGN KEY ( PURCHASE_REQUEST_ID )
        REFERENCES PURCHASE_REQUESTS ( PURCHASE_REQUEST_ID )
    , CONSTRAINT FK_PUR_ITEM_MAT FOREIGN KEY ( MATERIAL_ID )
        REFERENCES MATERIALS ( MATERIAL_ID )
);

CREATE SEQUENCE SEQ_PUR_REQ_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE PURCHASE_REQUEST_ITEMS IS
    '발주 요청 상세';
COMMENT ON COLUMN PURCHASE_REQUEST_ITEMS.PURCHASE_REQUEST_ITEM_ID IS
    '발주 요청 상세 ID';
COMMENT ON COLUMN PURCHASE_REQUEST_ITEMS.PURCHASE_REQUEST_ID IS
    '발주 요청 ID';
COMMENT ON COLUMN PURCHASE_REQUEST_ITEMS.MATERIAL_ID IS
    '자재 ID';
COMMENT ON COLUMN PURCHASE_REQUEST_ITEMS.MATERIAL_NAME_SNAPSHOT IS
    '자재명 스냅샷';
COMMENT ON COLUMN PURCHASE_REQUEST_ITEMS.UNIT_PRICE_SNAPSHOT IS
    '단가 스냅샷';
COMMENT ON COLUMN PURCHASE_REQUEST_ITEMS.REQUEST_QUANTITY IS
    '요청 수량';
COMMENT ON COLUMN PURCHASE_REQUEST_ITEMS.APPROVED_QUANTITY IS
    '승인 수량';
COMMENT ON COLUMN PURCHASE_REQUEST_ITEMS.ITEM_STATUS IS
    '품목 상태';
COMMENT ON COLUMN PURCHASE_REQUEST_ITEMS.REJECT_REASON IS
    '품목 반려 사유';
COMMENT ON COLUMN PURCHASE_REQUEST_ITEMS.SUBTOTAL_AMOUNT IS
    '소계 금액';


-- 발주 상태 이력
CREATE TABLE PURCHASE_REQUEST_HISTORIES (
    PURCHASE_REQUEST_HISTORY_ID NUMBER NOT NULL
    , PURCHASE_REQUEST_ID         NUMBER NOT NULL
    , FROM_STATUS                 VARCHAR2(30)
    , TO_STATUS                   VARCHAR2(30) NOT NULL
    , REASON                      VARCHAR2(1000)
    , CREATED_BY                  NUMBER NOT NULL
    , CREATED_AT                  DATE DEFAULT SYSDATE NOT NULL
    , CONSTRAINT PK_PUR_REQ_HIST PRIMARY KEY ( PURCHASE_REQUEST_HISTORY_ID )
    , CONSTRAINT FK_PUR_HIST_REQ FOREIGN KEY ( PURCHASE_REQUEST_ID )
        REFERENCES PURCHASE_REQUESTS ( PURCHASE_REQUEST_ID )
    , CONSTRAINT FK_PUR_HIST_USER FOREIGN KEY ( CREATED_BY )
        REFERENCES USERS ( USER_ID )
);

CREATE SEQUENCE SEQ_PUR_REQ_HIST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE PURCHASE_REQUEST_HISTORIES IS
    '발주 요청 상태 이력';
COMMENT ON COLUMN PURCHASE_REQUEST_HISTORIES.PURCHASE_REQUEST_HISTORY_ID IS
    '발주 요청 상태 이력 ID';
COMMENT ON COLUMN PURCHASE_REQUEST_HISTORIES.PURCHASE_REQUEST_ID IS
    '발주 요청 ID';
COMMENT ON COLUMN PURCHASE_REQUEST_HISTORIES.FROM_STATUS IS
    '변경 전 상태';
COMMENT ON COLUMN PURCHASE_REQUEST_HISTORIES.TO_STATUS IS
    '변경 후 상태';
COMMENT ON COLUMN PURCHASE_REQUEST_HISTORIES.REASON IS
    '상태 변경 사유';
COMMENT ON COLUMN PURCHASE_REQUEST_HISTORIES.CREATED_BY IS
    '등록자 ID';
COMMENT ON COLUMN PURCHASE_REQUEST_HISTORIES.CREATED_AT IS
    '등록일시';


-- =========================================================
-- 4. 입고
-- =========================================================

-- 입고
CREATE TABLE RECEIPTS (
    RECEIPT_ID          NUMBER NOT NULL
    , PURCHASE_REQUEST_ID NUMBER NOT NULL
    , STORE_ID            NUMBER NOT NULL
    , RECEIPT_MEMO        VARCHAR2(1000)
    , RECEIVED_BY         NUMBER NOT NULL
    , RECEIVED_AT         DATE DEFAULT SYSDATE NOT NULL
    , CONSTRAINT PK_RECEIPTS PRIMARY KEY ( RECEIPT_ID )
    , CONSTRAINT FK_RECEIPTS_PUR_REQ FOREIGN KEY ( PURCHASE_REQUEST_ID )
        REFERENCES PURCHASE_REQUESTS ( PURCHASE_REQUEST_ID )
    , CONSTRAINT FK_RECEIPTS_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
    , CONSTRAINT FK_RECEIPTS_USER FOREIGN KEY ( RECEIVED_BY )
        REFERENCES USERS ( USER_ID )
);

CREATE SEQUENCE SEQ_RECEIPT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE RECEIPTS IS
    '입고';
COMMENT ON COLUMN RECEIPTS.RECEIPT_ID IS
    '입고 ID';
COMMENT ON COLUMN RECEIPTS.PURCHASE_REQUEST_ID IS
    '발주 요청 ID';
COMMENT ON COLUMN RECEIPTS.STORE_ID IS
    '점포 ID';
COMMENT ON COLUMN RECEIPTS.RECEIPT_MEMO IS
    '입고 메모';
COMMENT ON COLUMN RECEIPTS.RECEIVED_BY IS
    '입고 처리자 ID';
COMMENT ON COLUMN RECEIPTS.RECEIVED_AT IS
    '입고 처리일시';


-- 입고 상세
CREATE TABLE RECEIPT_ITEMS (
    RECEIPT_ITEM_ID          NUMBER NOT NULL
    , RECEIPT_ID               NUMBER NOT NULL
    , PURCHASE_REQUEST_ITEM_ID NUMBER NOT NULL
    , MATERIAL_ID              NUMBER NOT NULL
    , APPROVED_QUANTITY        NUMBER(10) NOT NULL
    , RECEIVED_QUANTITY        NUMBER(10) NOT NULL
    , SHORTAGE_QUANTITY        NUMBER(10) DEFAULT 0 NOT NULL
    , RECEIPT_ITEM_MEMO        VARCHAR2(1000)
    , CONSTRAINT PK_RECEIPT_ITEMS PRIMARY KEY ( RECEIPT_ITEM_ID )
    , CONSTRAINT UK_RECEIPT_ITEM_PUR UNIQUE ( RECEIPT_ID
    , PURCHASE_REQUEST_ITEM_ID )
    , CONSTRAINT FK_RECEIPT_ITEM_RECEIPT FOREIGN KEY ( RECEIPT_ID )
        REFERENCES RECEIPTS ( RECEIPT_ID )
    , CONSTRAINT FK_RECEIPT_ITEM_PUR_ITEM FOREIGN KEY ( PURCHASE_REQUEST_ITEM_ID )
        REFERENCES PURCHASE_REQUEST_ITEMS ( PURCHASE_REQUEST_ITEM_ID )
    , CONSTRAINT FK_RECEIPT_ITEM_MAT FOREIGN KEY ( MATERIAL_ID )
        REFERENCES MATERIALS ( MATERIAL_ID )
);

CREATE SEQUENCE SEQ_RECEIPT_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE RECEIPT_ITEMS IS
    '입고 상세';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIPT_ITEM_ID IS
    '입고 상세 ID';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIPT_ID IS
    '입고 ID';
COMMENT ON COLUMN RECEIPT_ITEMS.PURCHASE_REQUEST_ITEM_ID IS
    '발주 요청 상세 ID';
COMMENT ON COLUMN RECEIPT_ITEMS.MATERIAL_ID IS
    '자재 ID';
COMMENT ON COLUMN RECEIPT_ITEMS.APPROVED_QUANTITY IS
    '승인 수량';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIVED_QUANTITY IS
    '실수령 수량';
COMMENT ON COLUMN RECEIPT_ITEMS.DEFECT_QUANTITY IS
    '불량 수량';
COMMENT ON COLUMN RECEIPT_ITEMS.RECEIPT_ITEM_MEMO IS
    '입고 상세 메모';


-- =========================================================
-- 5. 점포 마감
-- =========================================================

-- 점포 마감
CREATE TABLE STORE_CLOSINGS (
    STORE_CLOSING_ID NUMBER NOT NULL
    , STORE_ID         NUMBER NOT NULL
    , BUSINESS_DATE    DATE NOT NULL
    , CLOSING_MEMO     VARCHAR2(1000)
    , CLOSED_BY        NUMBER NOT NULL
    , CLOSED_AT        DATE DEFAULT SYSDATE NOT NULL
    , CONSTRAINT PK_STORE_CLS PRIMARY KEY ( STORE_CLOSING_ID )
    , CONSTRAINT UK_STORE_CLS_DATE UNIQUE ( STORE_ID
    , BUSINESS_DATE )
    , CONSTRAINT FK_STORE_CLS_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
    , CONSTRAINT FK_STORE_CLS_USER FOREIGN KEY ( CLOSED_BY )
        REFERENCES USERS ( USER_ID )
);

CREATE SEQUENCE SEQ_STORE_CLS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORE_CLOSINGS IS
    '점포 마감';
COMMENT ON COLUMN STORE_CLOSINGS.STORE_CLOSING_ID IS
    '점포 마감 ID';
COMMENT ON COLUMN STORE_CLOSINGS.STORE_ID IS
    '점포 ID';
COMMENT ON COLUMN STORE_CLOSINGS.BUSINESS_DATE IS
    '영업일';
COMMENT ON COLUMN STORE_CLOSINGS.CLOSING_MEMO IS
    '마감 메모';
COMMENT ON COLUMN STORE_CLOSINGS.CLOSED_BY IS
    '마감 처리자 ID';
COMMENT ON COLUMN STORE_CLOSINGS.CLOSED_AT IS
    '마감 처리일시';


-- 점포 마감 상세
CREATE TABLE STORE_CLOSING_ITEMS (
    STORE_CLOSING_ITEM_ID NUMBER NOT NULL
    , STORE_CLOSING_ID      NUMBER NOT NULL
    , MATERIAL_ID           NUMBER NOT NULL
    , SYSTEM_QUANTITY       NUMBER(10) NOT NULL
    , PHYSICAL_QUANTITY     NUMBER(10) NOT NULL
    , DISPOSAL_QUANTITY     NUMBER(10) DEFAULT 0 NOT NULL
    , DIFFERENCE_QUANTITY   NUMBER(10) NOT NULL
    , CLOSING_ITEM_MEMO     VARCHAR2(1000)
    , CONSTRAINT PK_STORE_CLS_ITEM PRIMARY KEY ( STORE_CLOSING_ITEM_ID )
    , CONSTRAINT UK_STORE_CLS_ITEM_MAT UNIQUE ( STORE_CLOSING_ID
    , MATERIAL_ID )
    , CONSTRAINT FK_STORE_CLS_ITEM_CLS FOREIGN KEY ( STORE_CLOSING_ID )
        REFERENCES STORE_CLOSINGS ( STORE_CLOSING_ID )
    , CONSTRAINT FK_STORE_CLS_ITEM_MAT FOREIGN KEY ( MATERIAL_ID )
        REFERENCES MATERIALS ( MATERIAL_ID )
);

CREATE SEQUENCE SEQ_STORE_CLS_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STORE_CLOSING_ITEMS IS
    '점포 마감 상세';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.STORE_CLOSING_ITEM_ID IS
    '점포 마감 상세 ID';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.STORE_CLOSING_ID IS
    '점포 마감 ID';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.MATERIAL_ID IS
    '자재 ID';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.SYSTEM_QUANTITY IS
    '전산 재고 수량';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.PHYSICAL_QUANTITY IS
    '실재고 수량';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.DISPOSAL_QUANTITY IS
    '폐기 수량';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.DIFFERENCE_QUANTITY IS
    '재고 차이 수량';
COMMENT ON COLUMN STORE_CLOSING_ITEMS.CLOSING_ITEM_MEMO IS
    '마감 상세 메모';


-- =========================================================
-- 6. 재고 변동 이력
-- =========================================================

-- 재고 변동 이력
CREATE TABLE INVENTORY_TRANSACTIONS (
    INVENTORY_TRANSACTION_ID NUMBER NOT NULL
    , STORE_ID                 NUMBER NOT NULL
    , SOURCE_TYPE              VARCHAR2(30) NOT NULL
    , SOURCE_ID                NUMBER NOT NULL
    , TRANSACTION_MEMO         VARCHAR2(1000)
    , CREATED_BY               NUMBER NOT NULL
    , CREATED_AT               DATE DEFAULT SYSDATE NOT NULL
    , CONSTRAINT PK_INV_TX PRIMARY KEY ( INVENTORY_TRANSACTION_ID )
    , CONSTRAINT CK_INV_TX_SOURCE
        CHECK ( SOURCE_TYPE IN ( 'RECEIPT', 'STORE_CLOSING', 'ADJUSTMENT' ) )
    , CONSTRAINT FK_INV_TX_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
    , CONSTRAINT FK_INV_TX_USER FOREIGN KEY ( CREATED_BY )
        REFERENCES USERS ( USER_ID )
);

CREATE SEQUENCE SEQ_INV_TX START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INVENTORY_TRANSACTIONS IS
    '재고 변동 이력';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.INVENTORY_TRANSACTION_ID IS
    '재고 변동 이력 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.STORE_ID IS
    '점포 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.SOURCE_TYPE IS
    '원천 업무 유형';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.SOURCE_ID IS
    '원천 업무 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.TRANSACTION_MEMO IS
    '재고 변동 메모';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.CREATED_BY IS
    '등록자 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.CREATED_AT IS
    '등록일시';


-- 재고 변동 이력 상세
CREATE TABLE INVENTORY_TRANSACTION_ITEMS (
    INVENTORY_TRANSACTION_ITEM_ID NUMBER NOT NULL
    , INVENTORY_TRANSACTION_ID      NUMBER NOT NULL
    , MATERIAL_ID                   NUMBER NOT NULL
    , BEFORE_QUANTITY               NUMBER(10) NOT NULL
    , CHANGE_QUANTITY               NUMBER(10) NOT NULL
    , AFTER_QUANTITY                NUMBER(10) NOT NULL
    , CONSTRAINT PK_INV_TX_ITEM PRIMARY KEY ( INVENTORY_TRANSACTION_ITEM_ID )
    , CONSTRAINT UK_INV_TX_ITEM_MAT UNIQUE ( INVENTORY_TRANSACTION_ID
    , MATERIAL_ID )
    , CONSTRAINT FK_INV_TX_ITEM_TX FOREIGN KEY ( INVENTORY_TRANSACTION_ID )
        REFERENCES INVENTORY_TRANSACTIONS ( INVENTORY_TRANSACTION_ID )
    , CONSTRAINT FK_INV_TX_ITEM_MAT FOREIGN KEY ( MATERIAL_ID )
        REFERENCES MATERIALS ( MATERIAL_ID )
);

CREATE SEQUENCE SEQ_INV_TX_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INVENTORY_TRANSACTION_ITEMS IS
    '재고 변동 이력 상세';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.INVENTORY_TRANSACTION_ITEM_ID IS
    '재고 변동 이력 상세 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.INVENTORY_TRANSACTION_ID IS
    '재고 변동 이력 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.MATERIAL_ID IS
    '자재 ID';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.BEFORE_QUANTITY IS
    '변경 전 수량';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.CHANGE_QUANTITY IS
    '변경 수량';
COMMENT ON COLUMN INVENTORY_TRANSACTION_ITEMS.AFTER_QUANTITY IS
    '변경 후 수량';


-- =========================================================
-- 7. 공지사항
-- =========================================================

-- 공지사항
CREATE TABLE NOTICES (
    NOTICE_ID  NUMBER NOT NULL
    , TITLE      VARCHAR2(200) NOT NULL
    , CONTENT    CLOB NOT NULL
    , DELETED_AT DATE
    , CREATED_BY NUMBER NOT NULL
    , CREATED_AT DATE DEFAULT SYSDATE NOT NULL
    , UPDATED_BY NUMBER
    , UPDATED_AT DATE
    , CONSTRAINT PK_NOTICES PRIMARY KEY ( NOTICE_ID )
    , CONSTRAINT FK_NOTICES_USER FOREIGN KEY ( CREATED_BY )
        REFERENCES USERS ( USER_ID )
);

CREATE SEQUENCE SEQ_NOTICE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE NOTICES IS
    '공지사항';
COMMENT ON COLUMN NOTICES.NOTICE_ID IS
    '공지사항 ID';
COMMENT ON COLUMN NOTICES.TITLE IS
    '제목';
COMMENT ON COLUMN NOTICES.CONTENT IS
    '내용';
COMMENT ON COLUMN NOTICES.DELETED_AT IS
    '삭제일시';
COMMENT ON COLUMN NOTICES.CREATED_BY IS
    '등록자 ID';
COMMENT ON COLUMN NOTICES.CREATED_AT IS
    '등록일시';
COMMENT ON COLUMN NOTICES.UPDATED_BY IS
    '수정자 ID';
COMMENT ON COLUMN NOTICES.UPDATED_AT IS
    '수정일시';


-- 공지사항 파일
CREATE TABLE NOTICE_FILES (
    NOTICE_FILE_ID NUMBER NOT NULL
    , NOTICE_ID      NUMBER NOT NULL
    , FILE_ID        NUMBER NOT NULL
    , DELETED_AT     DATE
    , CREATED_AT     DATE DEFAULT SYSDATE NOT NULL
    , CONSTRAINT PK_NOTICE_FILES PRIMARY KEY ( NOTICE_FILE_ID )
    , CONSTRAINT UK_NOTICE_FILE UNIQUE ( NOTICE_ID
    , FILE_ID )
    , CONSTRAINT FK_NOTICE_FILE_NOTICE FOREIGN KEY ( NOTICE_ID )
        REFERENCES NOTICES ( NOTICE_ID )
    , CONSTRAINT FK_NOTICE_FILE_FILE FOREIGN KEY ( FILE_ID )
        REFERENCES FILES ( FILE_ID )
);

CREATE SEQUENCE SEQ_NOTICE_FILE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE NOTICE_FILES IS
    '공지사항 파일';
COMMENT ON COLUMN NOTICE_FILES.NOTICE_FILE_ID IS
    '공지사항 파일 ID';
COMMENT ON COLUMN NOTICE_FILES.NOTICE_ID IS
    '공지사항 ID';
COMMENT ON COLUMN NOTICE_FILES.FILE_ID IS
    '파일 ID';
COMMENT ON COLUMN NOTICE_FILES.DELETED_AT IS
    '삭제일시';
COMMENT ON COLUMN NOTICE_FILES.CREATED_AT IS
    '등록일시';


-- =========================================================
-- 8. 문의사항
-- =========================================================

-- 문의사항
CREATE TABLE INQUIRIES (
    INQUIRY_ID     NUMBER NOT NULL
    , STORE_ID       NUMBER NOT NULL
    , TITLE          VARCHAR2(200) NOT NULL
    , CONTENT        CLOB NOT NULL
    , STATUS         VARCHAR2(20) DEFAULT 'WAITING' NOT NULL
    , ANSWER_CONTENT CLOB
    , ANSWERED_BY    NUMBER
    , ANSWERED_AT    DATE
    , DELETED_AT     DATE
    , CREATED_BY     NUMBER NOT NULL
    , CREATED_AT     DATE DEFAULT SYSDATE NOT NULL
    , UPDATED_BY     NUMBER
    , UPDATED_AT     DATE
    , CONSTRAINT PK_INQUIRIES PRIMARY KEY ( INQUIRY_ID )
    , CONSTRAINT CK_INQUIRIES_STATUS CHECK ( STATUS IN ( 'WAITING', 'ANSWERED' ) )
    , CONSTRAINT FK_INQUIRIES_STORE FOREIGN KEY ( STORE_ID )
        REFERENCES STORES ( STORE_ID )
    , CONSTRAINT FK_INQUIRIES_USER FOREIGN KEY ( CREATED_BY )
        REFERENCES USERS ( USER_ID )
    , CONSTRAINT FK_INQUIRIES_ANS_USER FOREIGN KEY ( ANSWERED_BY )
        REFERENCES USERS ( USER_ID )
);

CREATE SEQUENCE SEQ_INQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INQUIRIES IS
    '문의사항';
COMMENT ON COLUMN INQUIRIES.INQUIRY_ID IS
    '문의사항 ID';
COMMENT ON COLUMN INQUIRIES.STORE_ID IS
    '점포 ID';
COMMENT ON COLUMN INQUIRIES.TITLE IS
    '제목';
COMMENT ON COLUMN INQUIRIES.CONTENT IS
    '내용';
COMMENT ON COLUMN INQUIRIES.STATUS IS
    '문의 상태';
COMMENT ON COLUMN INQUIRIES.ANSWER_CONTENT IS
    '답변 내용';
COMMENT ON COLUMN INQUIRIES.ANSWERED_BY IS
    '답변자 ID';
COMMENT ON COLUMN INQUIRIES.ANSWERED_AT IS
    '답변일시';
COMMENT ON COLUMN INQUIRIES.DELETED_AT IS
    '삭제일시';
COMMENT ON COLUMN INQUIRIES.CREATED_BY IS
    '등록자 ID';
COMMENT ON COLUMN INQUIRIES.CREATED_AT IS
    '등록일시';
COMMENT ON COLUMN INQUIRIES.UPDATED_BY IS
    '수정자 ID';
COMMENT ON COLUMN INQUIRIES.UPDATED_AT IS
    '수정일시';


-- 문의사항 파일
CREATE TABLE INQUIRY_FILES (
    INQUIRY_FILE_ID NUMBER NOT NULL
    , INQUIRY_ID      NUMBER NOT NULL
    , FILE_ID         NUMBER NOT NULL
    , ATTACH_TARGET   VARCHAR2(20) NOT NULL
    , DELETED_AT      DATE
    , CREATED_AT      DATE DEFAULT SYSDATE NOT NULL
    , CONSTRAINT PK_INQ_FILES PRIMARY KEY ( INQUIRY_FILE_ID )
    , CONSTRAINT UK_INQ_FILE_TARGET UNIQUE ( INQUIRY_ID
    , FILE_ID
    , ATTACH_TARGET )
    , CONSTRAINT CK_INQ_FILE_TARGET CHECK ( ATTACH_TARGET IN ( 'QUESTION', 'ANSWER' ) )
    , CONSTRAINT FK_INQ_FILE_INQ FOREIGN KEY ( INQUIRY_ID )
        REFERENCES INQUIRIES ( INQUIRY_ID )
    , CONSTRAINT FK_INQ_FILE_FILE FOREIGN KEY ( FILE_ID )
        REFERENCES FILES ( FILE_ID )
);

CREATE SEQUENCE SEQ_INQ_FILE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE INQUIRY_FILES IS
    '문의사항 파일';
COMMENT ON COLUMN INQUIRY_FILES.INQUIRY_FILE_ID IS
    '문의사항 파일 ID';
COMMENT ON COLUMN INQUIRY_FILES.INQUIRY_ID IS
    '문의사항 ID';
COMMENT ON COLUMN INQUIRY_FILES.FILE_ID IS
    '파일 ID';
COMMENT ON COLUMN INQUIRY_FILES.ATTACH_TARGET IS
    '첨부 대상';
COMMENT ON COLUMN INQUIRY_FILES.DELETED_AT IS
    '삭제일시';
COMMENT ON COLUMN INQUIRY_FILES.CREATED_AT IS
    '등록일시';


-- =========================================================
-- 9. 데이터 시딩
-- =========================================================

-- 관리자 계정
INSERT INTO USERS (
    USER_ID
    , LOGIN_ID
    , PASSWORD
    , USER_NAME
    , PHONE
    , EMAIL
    , ROLE
    , CREATED_BY
    , UPDATED_BY
    , UPDATED_AT
) VALUES ( SEQ_USER.NEXTVAL
         , 'admin'
         , 'adminpass' -- TODO: 해시된 비밀번호로 수정
         , '관리자'
         , '010-0000-0000'
         , 'admin@burgerstack.com'
         , 'ADMIN'
         , 1
         , 1
         , SYSDATE );

-- 점주 계정 1
INSERT INTO USERS (
    USER_ID
    , LOGIN_ID
    , PASSWORD
    , USER_NAME
    , PHONE
    , EMAIL
    , CREATED_BY
    , UPDATED_BY
    , UPDATED_AT
) VALUES ( SEQ_USER.NEXTVAL
         , 'owner01'
         , 'pass01' -- TODO: 해시된 비밀번호로 수정
         , '홍길동'
         , '010-1234-5678'
         , 'gd.hong@burgerstack.com'
         , 1
         , 1
         , SYSDATE );


-- 커밋
COMMIT;
