-- 공지사항 더미
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지1','내용1',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지2','내용2',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지3','내용3',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지4','내용4',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지5','내용5',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지6','내용6',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지7','내용7',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지8','내용8',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지9','내용9',NULL,1,SYSDATE,NULL,NULL);
INSERT INTO NOTICES VALUES (SEQ_NOTICE.NEXTVAL,'공지10','내용10',NULL,1,SYSDATE,NULL,NULL);

-- 공지사항 게시글수 조회
SELECT COUNT(*)
  FROM NOTICES
 WHERE DELETED_AT IS NULL;

-- 공지사항 전체 목록 조회
SELECT NOTICE_ID  AS noticeId
     , TITLE      AS title
     , CREATED_AT AS createdAt
  FROM NOTICES
 WHERE DELETED_AT IS NULL
 ORDER BY CREATED_AT DESC;
 
 
-- 공지사항 상세 조회
-- 추후 파일 조인 구문 추가
SELECT TITLE
     , CONTENT
     , CREATED_AT
  FROM NOTICES
 WHERE DELETED_AT = NULL
   AND NOTICE_ID = ?;

-- 공지사항 수정
-- 추후 파일 조인 구문 추가
UPDATE NOTICES
   SET TITLE = ?
     , CONTENT = ?
     , UPDATED_AT = ?
 WHERE DELETED_AT IS NULL
   AND NOTICE_ID = ?;
   
-- 공지사항 삭제
UPDATE NOTICES
   SET DELETED_AT = ?
 WHERE DELETED_AT IS NULL
   AND NOTICE_ID = ?;
   
   
